### PR TITLE
Refactor in progress

### PR DESCRIPTION
**Pull request by apex-omontgomery**

### CODE REVIEW

**Comment by apex-omontgomery** [comment]
Will be creating new pull request with other changes shortly. Just wanted to put this out there for your to see.

**Comment by HadManySons** [comment]
I like what you've done, but it isn't error free:

Traceback (most recent call last):
  File ".\AFExcuse.py", line 123, in <module>
    main()
  File ".\AFExcuse.py", line 96, in main
    auth_client = RedditAuthenticate('ExcusesCreds.txt', logging_object)
  File ".\AFExcuse.py", line 63, in __init__
    self.credentails = LoadCredentials(cred_file_name, logging_object).get_credentials()
  File ".\AFExcuse.py", line 44, in __init__
    self.credentials = self.load_creds(cred_file_name, logging_object)
  File ".\AFExcuse.py", line 50, in load_creds
    return dict(line.replace('\n', '').split('=') for line in loaded_file)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

That being said, I really should have just dumped the credentials into a .py file and import them as variables instead of trying to read a text file.  If you want to convert the ExcuseCreds.txt to ExcuseCreds.py, that will probably clean everything up. Or make it so that I can edit this pull request I can do it myself.

**Comment by apex-omontgomery** [comment]
Yeah, I'm working on it right now. 
make sure you change your ExcusesCredts.txt to the format:
var_name=variable.  it looks like after removing the new line and splitting it's not finding both values. This way you can flatten the dictioary and feed into the file.

**Comment by apex-omontgomery** [comment]
user_agent=USER_AGENT
client_id=CLIENT_ID
client_secret=CLIENT_SECRET
username=USERNAME
password=PASSWORD

**Pull request closed without merging**
